apiVersion: app.kiegroup.org/v2
kind: KieApp
metadata:
  name: my-decision-svc-design-time
spec:
  environment: rhdm-authoring
  commonConfig:
    adminUser: dmAdmin
    adminPassword: dmAdmin
  objects:
    console:
      resources:
        limits:
          cpu: "1000m"
          memory: "2Gi"
        requests:
          cpu: "1000m"
          memory: "2Gi"