apiVersion: app.kiegroup.org/v2
kind: KieApp
metadata:
  name: my-process-app
spec:
  environment: rhpam-authoring
  commonConfig:
    adminUser: pamAdmin
    adminPassword: pamAdmin
  objects:
    console:
      resources:
        limits:
          cpu: "1000m"
          memory: "2Gi"
        requests:
          cpu: "1000m"
          memory: "2Gi"
    servers:
      - database:
          size: 5Gi
          type: postgresql