apiVersion: app.kiegroup.org/v2
kind: KieApp
metadata:
  name: my-process-svc
spec:
  environment: rhpam-authoring
  commonConfig:
    adminUser: pamAdmin
    adminPassword: pamAdmin
  truststore:
    openshiftCaBundle: true
  auth:
    sso:
      adminPassword: <PASSWORD>
      adminUser: <USER>
      realm: pam-realm
      url: 'https://<SSO_DOMAIN>/auth/'
      disableSSLCertValidation: true
      principalAttribute: preferred_username
  objects:
    console:
      routeHostname: business-central.<my-openshift-cluster.mydomain.com>
      ssoClient:
        name: bc-client
        secret: bc-client-secret
      resources:
        limits:
          cpu: "4000m"
          memory: "4Gi"
        requests:
          cpu: "4000m"
          memory: "4Gi"
    servers:
      - name: my-process-svc-kieserver
        routeHostname: kie-server.<my-openshift-cluster.mydomain.com>
        ssoClient:
          name: ks-client
          secret: ks-client-secret
        database:
          size: 5Gi
          type: postgresql